CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    contact_number TEXT,
    address TEXT,
    area_pin_code TEXT,
    service_details TEXT,
    service_date TEXT,
    service_timing TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts" ON public.bookings FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public select" ON public.bookings FOR SELECT TO public USING (true);
